In [71]:
import os
import pickle
import numpy as np

subj = 'sub-46'
subjectid = 'sub-46'
subject = subjectid
depth = 'GM'
project = 'PROJECT_EGRET-AAA'
space = 'fsnative'
roi = ['all']
r2_thr = 0.1
target_visual_area = 2
source_visual_area = 1
hemi = 'rh'
delineation = 'manualdelin'
atlas = 'manual'
denoising = 'nordic'
task = 'RET'

file_path = f'/Users/federicacardillo/Documents/GitHub/OBJ_MCMC_CF/OBJ_MCMC_CF/results/{subj}/{hemi}/V{target_visual_area}->V{source_visual_area}/best_fits.csv'  # Update with the actual path to your CSV file

MAIN_PATH = '/Volumes/FedericaCardillo/pre-processing/projects/PROJECT_EGRET-AAA/derivatives'
fs_dir = f"{MAIN_PATH}/freesurfer"
labels_path = f"{fs_dir}/{subj}/label/{hemi}.{delineation}.label"

# Define the pickle file path
filepath = os.path.join(MAIN_PATH, f'pRFM/{subjectid}/ses-02/{denoising}/model-{atlas}-nelder-mead-GM_desc-prf_params_{task}.pkl')

# Load the pickle file
def load_pickle(filepath):
    with open(filepath, 'rb') as f:
        data = pickle.load(f)
        return data
pickle_data = load_pickle(filepath) # model, settings, pred_tc, rois_mask

# Extract prf_params from the model
if pickle_data and 'model' in pickle_data:
    prf_params = pickle_data['model'].iterative_search_params
    print("\nType of prf_params:", type(prf_params)) # (19073, 8)
    r2 = prf_params[:, 7]  # Extract R2 values from column 7
    size = prf_params[:, 2]  # Extract pRF size values from column 2
    ecc = np.sqrt(prf_params[:, 1]**2 + prf_params[:, 0]**2)  # Calculate eccentricity
    angle = np.arctan2(prf_params[:, 1], prf_params[:, 0])  # Calculate polar angle




Type of prf_params: <class 'numpy.ndarray'>


In [72]:
import cortex
surfs = [cortex.polyutils.Surface(*d)
         for d in cortex.db.get_surf(subject, "fiducial")]

# First we need to import the surfaces for this subject
numel_left = surfs[0].pts.shape[0]
numel_right = surfs[1].pts.shape[0]
numel = numel_left + numel_right
print(numel)

prf_params=[np.array([])]
prf_params_vx=[np.array([])]
rois_list = []
rois_list = np.array([['V1','V2', 'V3'], [1, 2, 3]])
rois = [['V1','V2', 'V3']]
roi_verts=np.where(pickle_data['rois_mask']==1)
print(roi_verts)
print("Shape of rois_mask:", pickle_data['rois_mask'].shape)
prf_params=pickle_data['model'].iterative_search_params
print(prf_params.shape)
prf_params_vx=roi_verts[0]
prf_params_vx = np.arange(prf_params.shape[0])  # Assign all vertex indices
#print(prf_params_vx.shape)
prf_params_vx = np.arange(numel)  # Include all vertices from FreeSurfer surface
# Extract pRF model vertices for both hemispheres using idx_vls4
roi_verts = np.concatenate([
    np.where(idx_vls4 == rois_list[1, np.where(rois_list[0] == roi)[0]])[0]
    for roi in rois_list[0]
])
prf_params_vx = roi_verts

fs_dirPATH=f'{MAIN_PATH}/freesurfer'
idx_rois1, idx_vls1 = cortex.freesurfer.get_label(subject, label='benson14_eccen-0001',fs_dir=fs_dirPATH,hemisphere=('lh', 'rh'),verbose=True)
idx_rois4, idx_vls4 = cortex.freesurfer.get_label(subject, label='benson14_varea-0001',fs_dir=fs_dirPATH,hemisphere=('lh', 'rh'), verbose=True)

if atlas=='manual':
    idx_rois1, idx_vls1 = cortex.freesurfer.get_label(subject, label='benson14_eccen-0001',fs_dir=fs_dirPATH,hemisphere=('lh', 'rh'),verbose=True)
    idx_rois5, idx_vls5 = cortex.freesurfer.get_label(subject, label='manualdelin',fs_dir=fs_dirPATH,hemisphere=('lh','rh'),verbose=True)
    idx_vls4[idx_rois5]=idx_vls5

248511
(array([     0,      1,      2, ..., 248451, 248457, 248464]),)
Shape of rois_mask: (248511,)
(19073, 8)
looking for ['/Volumes/FedericaCardillo/pre-processing/projects/PROJECT_EGRET-AAA/derivatives/freesurfer/sub-46/label/lh.benson14_eccen-0001.label', '/Volumes/FedericaCardillo/pre-processing/projects/PROJECT_EGRET-AAA/derivatives/freesurfer/sub-46/label/rh.benson14_eccen-0001.label']


/var/folders/0k/zjsxn2197mdbzvx14lj8m0v00000gn/T/ipykernel_71592/895534794.py:27: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  np.where(idx_vls4 == rois_list[1, np.where(rois_list[0] == roi)[0]])[0]


looking for ['/Volumes/FedericaCardillo/pre-processing/projects/PROJECT_EGRET-AAA/derivatives/freesurfer/sub-46/label/lh.benson14_varea-0001.label', '/Volumes/FedericaCardillo/pre-processing/projects/PROJECT_EGRET-AAA/derivatives/freesurfer/sub-46/label/rh.benson14_varea-0001.label']
looking for ['/Volumes/FedericaCardillo/pre-processing/projects/PROJECT_EGRET-AAA/derivatives/freesurfer/sub-46/label/lh.benson14_eccen-0001.label', '/Volumes/FedericaCardillo/pre-processing/projects/PROJECT_EGRET-AAA/derivatives/freesurfer/sub-46/label/rh.benson14_eccen-0001.label']
looking for ['/Volumes/FedericaCardillo/pre-processing/projects/PROJECT_EGRET-AAA/derivatives/freesurfer/sub-46/label/lh.manualdelin.label', '/Volumes/FedericaCardillo/pre-processing/projects/PROJECT_EGRET-AAA/derivatives/freesurfer/sub-46/label/rh.manualdelin.label']


In [81]:
rois_list = []
rois_list = np.array([['V1','V2', 'V3'], [1, 2, 3]])
rois = [['V1','V2', 'V3']]

for r in range(rois[0].__len__()):
    r2 = prf_params[:, 7]  # Extract R2 values from column 7
    size = prf_params[:, 2]  # Extract pRF size values from column 2
    ecc = np.sqrt(prf_params[:, 1]**2 + prf_params[:, 0]**2)  # Calculate eccentricity
    angle = np.arctan2(prf_params[:, 1], prf_params[:, 0])  # Calculate polar angle
    roi=rois[0][r]
    print(roi)
    roi_idx = np.where(rois_list[0] == roi)[0]
    roi_verts = np.where(idx_vls4 == int(rois_list[1, roi_idx]))[0]

    # Ensure right hemisphere vertices are included
    idx = np.in1d(prf_params_vx, roi_verts) 
    
vertex_to_check = 7370  # The vertex ID we want to verify

for r in range(rois[0].__len__()):  
    roi = rois[0][r]  
    print(f"Checking visual area: {roi}")  
    
    # Get the corresponding visual area index
    roi_idx = np.where(roi == rois_list[0, :])[0]
    if len(roi_idx) == 0:
        print(f"  {roi} not found in rois_list")
        continue  # Skip if no match
    
    roi_verts = np.array(np.where(idx_vls4 == int(rois_list[1, roi_idx])))[0]  # Extract vertices in this region
    
    print(f"  Number of vertices in {roi}: {len(roi_verts)}")
    
    # Check if 6169 is in roi_verts
    if vertex_to_check in roi_verts:
        print(f"  ✅ Vertex {vertex_to_check} is present in {roi}!")
    else:
        print(f"  ❌ Vertex {vertex_to_check} is NOT present in {roi}.")

    # You can also print the matching indices if needed
    idx = np.in1d(prf_params_vx, roi_verts)  # Find matching indices
    matching_vertices = prf_params_vx[idx]  # Filtered list of vertices in this ROI

    if vertex_to_check in matching_vertices:
        print(f"  🔍 Vertex {vertex_to_check} has pRF parameters assigned in {roi}!")  

V1
V2
V3
Checking visual area: V1
  Number of vertices in V1: 7868
  ❌ Vertex 7370 is NOT present in V1.
Checking visual area: V2
  Number of vertices in V2: 7258
  ❌ Vertex 7370 is NOT present in V2.
Checking visual area: V3
  Number of vertices in V3: 5170
  ✅ Vertex 7370 is present in V3!


In [74]:
# Load CSV file and extract columns
import pandas as pd
df = pd.read_csv(file_path)
target_vertex_index = df.iloc[:, 0].values 
print(target_vertex_index)
print(target_vertex_index.shape)
source_vertex_index = df.iloc[:, 1].values 
print(source_vertex_index)
print(source_vertex_index.shape)


[  6747   7407   7370 ... 101014    255    256]
(1657,)
[116601   5467 123111 ... 102359    104    385]
(1657,)


In [82]:
# Extract visual area indices from idx_vls4
v1_vertices = np.where(idx_vls4 == 1)[0]  # V1 vertices
v2_vertices = np.where(idx_vls4 == 2)[0]  # V2 vertices

print(f"Total V1 vertices found: {len(v1_vertices)}")
print(f"Total V2 vertices found: {len(v2_vertices)}")

# Check if all target_vertex_index are actually in V2
v2_in_pickle = np.isin(target_vertex_index, v2_vertices)
v1_in_pickle = np.isin(source_vertex_index, v1_vertices)

# Count matches
v2_correct_count = np.sum(v2_in_pickle)
v1_correct_count = np.sum(v1_in_pickle)

print(f"✅ {v2_correct_count}/{len(target_vertex_index)} target vertices correctly assigned to V2.")
print(f"✅ {v1_correct_count}/{len(source_vertex_index)} source vertices correctly assigned to V1.")

# Identify missing or incorrect assignments
incorrect_v2 = target_vertex_index[~v2_in_pickle]
incorrect_v1 = source_vertex_index[~v1_in_pickle]

print(f"❌ {len(incorrect_v2)} target vertices (V2) are NOT in the pickle file as V2: {incorrect_v2[:10]}")
print(f"❌ {len(incorrect_v1)} source vertices (V1) are NOT in the pickle file as V1: {incorrect_v1[:10]}")

# Now, check if these vertices also exist in prf_params_vx (meaning they have pRF parameters assigned)
v2_with_prf = np.isin(target_vertex_index, prf_params_vx)
v1_with_prf = np.isin(source_vertex_index, prf_params_vx)

print(f"🔍 {np.sum(v2_with_prf)}/{len(target_vertex_index)} target vertices have pRF parameters assigned.")
print(f"🔍 {np.sum(v1_with_prf)}/{len(source_vertex_index)} source vertices have pRF parameters assigned.")

# Identify missing pRF parameter assignments
missing_v2_prf = target_vertex_index[~v2_with_prf]
missing_v1_prf = source_vertex_index[~v1_with_prf]

print(f"⚠️ {len(missing_v2_prf)} target vertices do NOT have pRF parameters: {missing_v2_prf[:10]}")
print(f"⚠️ {len(missing_v1_prf)} source vertices do NOT have pRF parameters: {missing_v1_prf[:10]}")

Total V1 vertices found: 7868
Total V2 vertices found: 7258
✅ 412/1657 target vertices correctly assigned to V2.
✅ 410/1657 source vertices correctly assigned to V1.
❌ 1245 target vertices (V2) are NOT in the pickle file as V2: [7407 7370 6732 6170 6169 7387 8012 7406 8044 8030]
❌ 1247 source vertices (V1) are NOT in the pickle file as V1: [116601   5467 123111   7292   5571   5571 123111   7305   3633  10446]
🔍 0/1657 target vertices have pRF parameters assigned.
🔍 0/1657 source vertices have pRF parameters assigned.
⚠️ 1657 target vertices do NOT have pRF parameters: [6747 7407 7370 6732 6170 6169 7387 8012 7406 8044]
⚠️ 1657 source vertices do NOT have pRF parameters: [116601   5467 123111   7292   5571   5571 123111   7305   3633  10446]
